[pytest]
addopts = -p no:tmpdir -p no:cacheprovider
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
norecursedirs = _pytest_tmp _pytest_basetemp .pytest_tmp pytest_tmp pytest_tmp_dir .pytest_cache
