"""
Pydantic schemas for emotion insights and trends.

These schemas capture aggregated data, such as emotion distribution over
time and supportive text generated by an LLM (to be added later).
"""

from datetime import datetime

from pydantic import BaseModel


class EmotionTrendPoint(BaseModel):
    """Represents aggregated emotion information for a time bucket."""

    timestamp: datetime
    dominant_emotion: str
    confidence: float | None = None


class InsightResponse(BaseModel):
    """
    High-level emotional insight for a user.

    `supportive_message` is intended to be generated by an LLM service.
    """

    user_id: str
    trend: list[EmotionTrendPoint]
    supportive_message: str | None = None

"""
Pydantic schemas for emotion insights and trends.

These schemas capture aggregated data, such as emotion distribution over
time and supportive text generated by an LLM (to be added later).
"""

from datetime import datetime

from pydantic import BaseModel


class EmotionTrendPoint(BaseModel):
    """Represents aggregated emotion information for a time bucket."""

    timestamp: datetime
    dominant_emotion: str
    confidence: float | None = None


class InsightResponse(BaseModel):
    """
    High-level emotional insight for a user.

    `supportive_message` is intended to be generated by an LLM service.
    """

    user_id: str
    trend: list[EmotionTrendPoint]
    supportive_message: str | None = None

